###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      restart: unless-stopped
      env_file:
        - ./.env.local
      image: mysql:8.0
      container_name: sesdashboard-mysql
      working_dir: /application
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - .:/application
        - sesdashboard-mysql-datavolume:/var/lib/mysql
      ports:
        - "8085:3306"
      networks:
        - fbnet

    sesdashboard:
      restart: unless-stopped
      build:
        context: .
      image: sesdashboard:local
      container_name: sesdashboard
      working_dir: /var/www/
      volumes:
        - '.:/var/www/'
      environment:
        VIRTUAL_HOST: ses.dashboard.fb.localhost
      env_file:
        - ./.env.local
      command: ["/bin/bash", "-c", "make init_within_container && apache2-foreground"]
      networks:
        - fbnet

volumes:
  sesdashboard-mysql-datavolume:
    driver: local


networks:
  fbnet:
    external: true
    name: fbnet
